INSERT INTO flight (f_code, f_name, source, destination) VALUES
('AA123', 'American Skyways-1', 'Atlanta', 'Dallas/Fort Worth'),
('DL4567', 'American Skyways-2', 'Denver','Chicago'),
('UA89', 'American Skyways-3', 'Los Angeles', 'New York (JFK)'),
('SW2345', 'American Skyways-4', 'Las Vegas', 'Orlando'),
('AS678', 'American Skyways-5', 'Charlotte', 'Miami'),
('B69012', 'American Skyways-6', 'Seattle/Tacoma', 'Newark'),
('WN34', 'American Skyways-7', 'San Francisco', 'Phoenix'),
('F9567', 'American Skyways-8', 'Houston', 'Boston'),
('NK8901', 'American Skyways-9', 'Minneapolis/St. Paul', 'Fort Lauderdale'),
('G42345', 'American Skyways-10', 'Detroit', 'New York (LGA)'),
('HA6789', 'American Skyways-11', 'Dallas/Fort Worth', 'Atlanta'),
('SY12', 'American Skyways-12', 'Chicago', 'Denver'),
('AC345', 'American Skyways-13', 'New York (JFK)', 'Los Angeles'),
('BA6789', 'American Skyways-14', 'Orlando', 'Las Vegas'),
('LH0123', 'American Skyways-15', 'Miami', 'Charlotte'),
('EK456', 'American Skyways-16', 'Newark', 'Seattle/Tacoma'),
('QR7890', 'American Skyways-17', 'Phoenix', 'San Francisco'),
('AF1234', 'American Skyways-18', 'Boston', 'Houston'),
('KL567', 'American Skyways-19', 'Fort Lauderdale', 'Minneapolis/St. Paul'),
('JL890', 'American Skyways-20', 'New York (LGA)', 'Detroit'),
('AA987', 'American Skyways-21', 'Atlanta', 'Houston'),
('DL6543', 'American Skyways-22', 'Los Angeles', 'Miami'),
('UA321', 'American Skyways-23', 'Chicago', 'Seattle/Tacoma'),
('SW1122', 'American Skyways-24', 'Las Vegas', 'Phoenix'),
('AS776', 'American Skyways-25', 'Charlotte', 'San Francisco');